### ISSUE TITLE
stringTest=dynamic is not leveraged for the comparison statement

### ISSUE THREAD

**Issue by veillette** [phetsims/number-compare#37] opened 2023-04-14 15:22 UTC
This is done as part of https://github.com/phetsims/qa/issues/934

As part of the QA process one must carry out a series of stringTest.

The following tests work well
https://phet-dev.colorado.edu/html/number-compare/1.0.0-rc.1/phet/number-compare_all_phet.html?stringTest=double
![image](https://user-images.githubusercontent.com/7633344/232083860-8d1224b9-968f-4ad3-8bac-45ae4d775192.png)

https://phet-dev.colorado.edu/html/number-compare/1.0.0-rc.1/phet/number-compare_all_phet.html?stringTest=O%20Canada
![image](https://user-images.githubusercontent.com/7633344/232084575-4634c6d6-8df3-4020-905d-6ce3a871cc31.png)

However, the comparison statement is impervious to the stringTest=dynamic
![image](https://user-images.githubusercontent.com/7633344/232085028-e7ffe310-8ebc-4e45-a36e-6350030807d9.png)

The comparison statement will clearly passed the spirit of the string test, but is is odd that the dynamic test does not seem to work.
Perhaps it is a problem with dynamic test itself, or the comparison statement is combining strings in a way that  the dynamic string test  cannot change.

**Comment by veillette** [comment] 2023-04-14 15:57
I should clarify. The comparison statement does not get updated while you use the arrow keys to change the strings using stringTest=dynamic.

However, if one carries an action in the sim afterwards, it does update itself.

![image](https://user-images.githubusercontent.com/7633344/232093297-80c214c1-637d-4711-bedd-59f5bf5142b0.png)


I think it is just a quirk of stringTest=dynamic.

**Comment by veillette** [comment] 2023-04-14 15:58
Hmm, I feel that is going into a rabbit hole that may not be very productive. Feel free to close.

**Comment by zepumph** [comment] 2023-04-14 15:58
Ahh excellent. Yes thanks. We did this manually in Number Play in https://github.com/phetsims/number-play/commit/3301f630c8554c8dba9d91c772264e74ff614824.

Let's do this here too. While perhaps we wouldn't necessarily need to cherry pick, it seems smartest, since we were just using localeProperty as a proxy for every dependent i18n stringProperty that could effect the comparison.

**Comment by zepumph** [comment] 2023-04-14 15:59
@veillette, please take a listen on master and unassign yourself if all is well.

**Comment by veillette** [comment] 2023-04-14 16:05
@zepumph I can confirm that it works on phettest.

**Comment by zepumph** [comment] 2023-04-14 21:11
Alright! We confirmed that this is fixed in 1.0.0-rc.2 closing

**Closed by zepumph** 2023-04-14 21:11 UTC
Labels: status:ready-for-review
