### ISSUE TITLE
Assertions failing in debug sim

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/number-compare#20] opened 2023-03-10 20:24 UTC
**Test device**
Samsung
**Operating System**
Win 11
**Browser**
Chrome
**Problem description**
For https://github.com/phetsims/qa/issues/917
When running a fuzz test on the debug version the sim this assertion appeared several times.

**Visuals**
![keepsshowingup](https://user-images.githubusercontent.com/41024075/224421458-067cee57-ca69-4748-bba6-3ba02a1d7063.png)

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Number Compare‬
URL: https://phet-dev.colorado.edu/html/number-compare/1.0.0-dev.4/phet/number-compare_all_phet.html
Version: 1.0.0-dev.4 2023-03-09 16:37:22 UTC
Features missing: applicationcache, applicationcache, touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
Language: en-US
Window: 1536x714
Pixel Ratio: 1.25/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 31 uniform: 4096
Texture: size: 8192 imageUnits: 32 (vertex: 32, combined: 64)
Max viewport: 8192x8192
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by chrisklus** [comment] 2023-03-15 01:08
Thanks @KatieWoe! I think this was actually the cause of https://github.com/phetsims/number-suite-common/issues/55, should be fixed in the above commits. Leaving self assigned to verify in the new dev version.

**Comment by chrisklus** [comment] 2023-03-15 01:34
I am not seeing this in dev.6, closing.

**Closed by chrisklus** 2023-03-15 01:34 UTC
Labels: type:bug

**Comment by chrisklus** [comment] 2023-03-15 15:04
The problem was the string to be read out for testing a voice in preferences was being stripped out during a build. @samreid helped me added a reference to it so that would not happen.
